export const SET_RECIPES = "SET_RECIPES";
export const GET_NAME_RECIPES = "GET_NAME_RECIPES";
export const POST_RECIPE = "POST_RECIPE";
export const RECIPE_LOADING = "RECIPE_LOADING";
export const SET_RECIPE_FAIL = "SET_RECIPE_FAIL";
export const GET_RECIPE_DETAIL = "GET_RECIPE_DETAIL";
export const SET_DIETS = "SET_DIETS";
